[book]
authors = ["Nick Rossik"]
language = "ru"
multilingual = false
src = "src"
title = "Structured Concurrency не магия"

[build]
build-dir = "docs"
create-missing = false

[output.html.code.hidelines]
swift = "#"
cpp = "#"

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[preprocessor]
[preprocessor.alerts]
[preprocessor.mermaid]
command = "mdbook-mermaid"
